export type BlogType = {
    metaTitle:string,
    metaDescription:string,
    banner:string,
    bannerAlt:string,
    bannerAlt_ar:string,
    pageTitle:string,
    pageTitle_ar:string,
    categories:{
        name:string,
        blogs:{
            title:string,
            title_ar:string,
            slug:string,
            category?:string,
            coverImage:string,
            coverImageAlt:string,
            thumbnail:string,
            thumbnailAlt:string,
            date?:string,
            content:string,
            createdAt:string,
            metaTitle:string,
            metaDescription:string,
        }[]
    }[]
}