export const BannerData = {
  BannerTitle: "Contact us",
  BannerImg: "/images/contact-us/banner.jpg",
};

export const OurSchoolsData = {
  title: "Our Schools",
  description:
    "BEAM’s Creative Science Schools are located in key communities of Dubai and Sharjah, such as Nad Al Sheba, Maliha, and Muwaileh",
  schools: [
    {
      title: "City Gate Tower",
      location: "Al Ittihad St, Sharjah",
      img: "/images/home/sc1.jpg",
    },
    {
      title: "American School of Creative Science",
      location: "Maliha Road, Sharjah",
      img: "/images/beam-schools/ascs-maliha.png",
    },
    {
      title: "American School of Creative Science",
      location: "Al Layyah, Sharjah",
      img: "/images/beam-schools/ascs-layyah.png",
    },
    {
      title: "International School of Creative Science",
      location: "Muwaileh, Sharjah",
      img: "/images/home/sc1.jpg",
    },
    {
      title: "American School of Creative Science",
      location: "Nad Al Sheba, Dubai",
      img: "/images/beam-schools/ascs-nas.png",
    },
    {
      title: "International School of Creative Science",
      location: "Nad Al Sheba, Dubai",
      img: "/images/home/sc2.jpg",
    },
  ],
};

export const schoolData = [
  {
    name: "American School of Creative Science – Nad Al Sheba",
    name_ar: "المدرسة الأمريكية للإبداع العلمي - ند الشبا",
    grades: [
      { en: "Pre-KG / FS1", ar: "Pre KG / FS1" },
      { en: "KG1 / FS2", ar: "KG1 / FS2" },
      { en: "KG2 / Year 1", ar: "KG2 / Year 1" },
      { en: "Grade 1 / Year 2", ar: "G1 / Year 2" },
      { en: "Grade 2 / Year 3", ar: "G2 / Year 3" },
      { en: "Grade 3 / Year 4", ar: "G3 / Year 4" },
      { en: "Grade 4 / Year 5", ar: "G4 / Year 5" },
      { en: "Grade 5 / Year 6", ar: "G5 / Year 6" },
      { en: "Grade 6 / Year 7", ar: "G6 / Year 7" },
      { en: "Grade 7 / Year 8", ar: "G7 / Year 8" },
      { en: "Grade 8 / Year 9", ar: "G8 / Year 9" },
      { en: "Grade 9 / Year 10", ar: "G9 / Year 10" },
      { en: "Grade 10 / Year 11", ar: "G10 / Year 11" },
      { en: "Grade 11 / Year 12", ar: "G11 / Year 12" },
      { en: "Grade 12 / Year 13", ar: "G12 / Year 13" },
    ],
  },
  {
    name: "American School of Creative Science – Maliha",
    name_ar: "المدرسة الأمريكية للإبداع العلمي - مليحة",
    grades: [
      { en: "Pre-KG / FS1", ar: "Pre KG / FS1" },
      { en: "KG1 / FS2", ar: "KG1 / FS2" },
      { en: "KG2 / Year 1", ar: "KG2 / Year 1" },
      { en: "Grade 1 / Year 2", ar: "G1 / Year 2" },
      { en: "Grade 2 / Year 3", ar: "G2 / Year 3" },
      { en: "Grade 3 / Year 4", ar: "G3 / Year 4" },
      { en: "Grade 4 / Year 5", ar: "G4 / Year 5" },
      { en: "Grade 5 / Year 6", ar: "G5 / Year 6" },
      { en: "Grade 6 / Year 7", ar: "G6 / Year 7" },
      { en: "Grade 7 / Year 8", ar: "G7 / Year 8" },
      { en: "Grade 8 / Year 9", ar: "G8 / Year 9" },
      { en: "Grade 9 / Year 10", ar: "G9 / Year 10" },
      { en: "Grade 10 / Year 11", ar: "G10 / Year 11" },
      { en: "Grade 11 / Year 12", ar: "G11 / Year 12" },
      { en: "Grade 12 / Year 13", ar: "G12 / Year 13" },
    ],
  },
  {
    name: "American School of Creative Science – Al Layyah",
    name_ar: "المدرسة الأمريكية للإبداع العلمي - اللية",
    grades: [
      { en: "Pre-KG / FS1", ar: "Pre KG / FS1" },
      { en: "KG1 / FS2", ar: "KG1 / FS2" },
      { en: "KG2 / Year 1", ar: "KG2 / Year 1" },
      { en: "Grade 1 / Year 2", ar: "G1 / Year 2" },
      { en: "Grade 2 / Year 3", ar: "G2 / Year 3" },
      { en: "Grade 3 / Year 4", ar: "G3 / Year 4" },
      { en: "Grade 4 / Year 5", ar: "G4 / Year 5" },
      { en: "Grade 5 / Year 6", ar: "G5 / Year 6" },
      { en: "Grade 6 / Year 7", ar: "G6 / Year 7" },
      { en: "Grade 7 / Year 8", ar: "G7 / Year 8" },
      { en: "Grade 8 / Year 9", ar: "G8 / Year 9" },
      { en: "Grade 9 / Year 10", ar: "G9 / Year 10" },
      { en: "Grade 10 / Year 11", ar: "G10 / Year 11" },
      { en: "Grade 11 / Year 12", ar: "G11 / Year 12" },
      { en: "Grade 12 / Year 13", ar: "G12 / Year 13" },
    ],
  },
  {
    name: "International School of Creative Science – Nad Al Sheba",
    name_ar: "مدرسة الإبداع العلمي الدولية - ند الشبا",
    grades: [
      { en: "Pre-KG / FS1", ar: "Pre KG / FS1" },
      { en: "KG1 / FS2", ar: "KG1 / FS2" },
      { en: "KG2 / Year 1", ar: "KG2 / Year 1" },
      { en: "Grade 1 / Year 2", ar: "G1 / Year 2" },
      { en: "Grade 2 / Year 3", ar: "G2 / Year 3" },
      { en: "Grade 3 / Year 4", ar: "G3 / Year 4" },
      { en: "Grade 4 / Year 5", ar: "G4 / Year 5" },
      { en: "Grade 5 / Year 6", ar: "G5 / Year 6" },
      { en: "Grade 6 / Year 7", ar: "G6 / Year 7" },
      { en: "Grade 7 / Year 8", ar: "G7 / Year 8" },
      { en: "Grade 8 / Year 9", ar: "G8 / Year 9" },
      { en: "Grade 9 / Year 10", ar: "G9 / Year 10" },
      { en: "Grade 10 / Year 11", ar: "G10 / Year 11" },
      { en: "Grade 11 / Year 12", ar: "G11 / Year 12" },
      { en: "Grade 12 / Year 13", ar: "G12 / Year 13" },
    ],
  },
  {
    name: "International School of Creative Science – Muwaileh",
    name_ar: "مدرسة الإبداع العلمي الدولية - مويلح",
    grades: [
      { en: "Pre-KG / FS1", ar: "Pre KG / FS1" },
      { en: "KG1 / FS2", ar: "KG1 / FS2" },
      { en: "KG2 / Year 1", ar: "KG2 / Year 1" },
      { en: "Grade 1 / Year 2", ar: "G1 / Year 2" },
      { en: "Grade 2 / Year 3", ar: "G2 / Year 3" },
      { en: "Grade 3 / Year 4", ar: "G3 / Year 4" },
      { en: "Grade 4 / Year 5", ar: "G4 / Year 5" },
      { en: "Grade 5 / Year 6", ar: "G5 / Year 6" },
      { en: "Grade 6 / Year 7", ar: "G6 / Year 7" },
      { en: "Grade 7 / Year 8", ar: "G7 / Year 8" },
      { en: "Grade 8 / Year 9", ar: "G8 / Year 9" },
      { en: "Grade 9 / Year 10", ar: "G9 / Year 10" },
      { en: "Grade 10 / Year 11", ar: "G10 / Year 11" },
      { en: "Grade 11 / Year 12", ar: "G11 / Year 12" },
      { en: "Grade 12 / Year 13", ar: "G12 / Year 13" },
    ],
  },
  {
    name: "International School of Creative Science – Bahrain",
    name_ar: "مدرسة الإبداع العلمي الدولية - البحرين",
    grades: [
      { en: "Pre-KG / FS1", ar: "Pre KG / FS1" },
      { en: "KG1 / FS2", ar: "KG1 / FS2" },
      { en: "KG2 / Year 1", ar: "KG2 / Year 1" },
      { en: "Grade 1 / Year 2", ar: "G1 / Year 2" },
      { en: "Grade 2 / Year 3", ar: "G2 / Year 3" },
      { en: "Grade 3 / Year 4", ar: "G3 / Year 4" },
      { en: "Grade 4 / Year 5", ar: "G4 / Year 5" },
      { en: "Grade 5 / Year 6", ar: "G5 / Year 6" },
      { en: "Grade 6 / Year 7", ar: "G6 / Year 7" },
      { en: "Grade 7 / Year 8", ar: "G7 / Year 8" },
      { en: "Grade 8 / Year 9", ar: "G8 / Year 9" },
      { en: "Grade 9 / Year 10", ar: "G9 / Year 10" },
      { en: "Grade 10 / Year 11", ar: "G10 / Year 11" },
      { en: "Grade 11 / Year 12", ar: "G11 / Year 12" },
      { en: "Grade 12 / Year 13", ar: "G12 / Year 13" },
    ],
  },
];

// export const GRADES = [
//   { en: "Pre-KG / FS1", ar: "Pre KG / FS1" },
//   { en: "KG1 / FS2", ar: "KG1 / FS2" },
//   { en: "KG2 / Year 1", ar: "KG2 / Year 1" },
//   { en: "Grade 1 / Year 2", ar: "G1 / Year 2" },
//   { en: "Grade 2 / Year 3", ar: "G2 / Year 3" },
//   { en: "Grade 3 / Year 4", ar: "G3 / Year 4" },
//   { en: "Grade 4 / Year 5", ar: "G4 / Year 5" },
//   { en: "Grade 5 / Year 6", ar: "G5 / Year 6" },
//   { en: "Grade 6 / Year 7", ar: "G6 / Year 7" },
//   { en: "Grade 7 / Year 8", ar: "G7 / Year 8" },
//   { en: "Grade 8 / Year 9", ar: "G8 / Year 9" },
//   { en: "Grade 9 / Year 10", ar: "G9 / Year 10" },
//   { en: "Grade 10 / Year 11", ar: "G10 / Year 11" },
//   { en: "Grade 11 / Year 12", ar: "G11 / Year 12" },
//   { en: "Grade 12 / Year 13", ar: "G12 / Year 13" },
// ];
