export type AccreditationProps = {
    metaTitle:string,
    metaDescription:string,
    banner:string,
    bannerAlt:string,
    bannerAlt_ar:string,
    pageTitle:string,
    pageTitle_ar:string,
    firstSection:{
        title:string,
        description:string,
        image:string,
        imageAlt:string,
    },
    categories:{
        name:string,
        accreditations:{
            title:string,
            description:string,
            image:string,
            imageAlt:string,
            category:string,
        }[]
    }[]
}